version: "3.9"

services:
  db:
    build:
      context: db
    ports:
      - "3306:3306"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ymoviehelper_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    tty: true

  api:
    build:
      context: api
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./api/YMovieHelper:/home/node/YMovieHelper
    tty: true
    working_dir: "/home/node/YMovieHelper"

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend/app:/home/node/app
      - exception-volumes:/home/node/app/node_modules

    working_dir: "/home/node/app"
    tty: true

volumes:
  exception-volumes:
